package com.example.schoolapp.control.utils

object Keys {
    const val USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
    const val rule = "rule"
    const val image = "image"
    const val SchoolWorker = "SchoolWorker"
    const val admin = "admin"
    const val cashier = "cashier"
    const val store = "store"
    const val owner = "owner"
    const val product = "product"
    const val profile = "profile"
    const val staffs = "staffs"
    const val meal_scanner = "meal scanner"
    const val add_products = "add products"
    const val scannedMealHistory = "scannedMealHistory"
    const val toStudentMeal = "ToStudentMeal"
    const val student = "student"
    const val meals = "meals"
    const val mealState = "mealState"
    const val currentMeal = "currentMeal"
    const val history = "history"
    const val school = "school"
    const val id = "id"
}